name: Alex Kane Design
favicon: null
layout_spectrum: 0.7147654104046524
typography_spectrum: 0.8012567383702844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5186141142621636
  lightness: 0.6096843467094004
  saturation: 0.8304570154286921
  rhythmicContrast: 0.8793339587282389
purpose: []
