name: Alex Kane Design
favicon: null
layout_spectrum: 0
typography_spectrum: 0.51912
title: Alex Kane Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edfcf6'
    - '#59ffb8'
    - '#ff506d'
    - '#005c2f'
    - '#a3ad8a'
  brandStrength: 0.1875
  lightness: 0.6096843467094004
  saturation: 0.8304570154286921
  rhythmicContrast: 1
purpose: []
