name: Alex Kane Design
favicon: null
layout_spectrum: 0.05175
typography_spectrum: 0.51912
title: Alex Kane Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c1f60'
    - '#b694c5'
    - '#5e4d8e'
    - '#7e67a9'
  brandStrength: 0.75
  lightness: 0.6096843467094004
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
